### ISSUE TITLE
ListenAndServeTLS

### ISSUE THREAD

**Issue by crhym3** [google/acme#14]
Add a helper func so that people can do something like `goacme.ListenAndServerTLS` instead of `http.ListenAndServerTLS`.

Thanks @bradrydzewski for the idea.

**Comment by bradrydzewski** [comment]
a slightly alternative approach would be to provide a custom implementation of `net.Listener`. This would allow you to do something like this:

```go
tlsListener := goacme.NewListener(...)

s := &http.Server{Addr: addr, Handler: handler}
s.Serve(tlsListener)
```

or like this:

```go
tlsListener := goacme.NewListener(...)
http.Serve(tlsListener, handler)
```
this might be a bit more flexible than providing an alternative `ListenAndServerTLS`

**Comment by crhym3** [comment]
Started working on this in https://go-review.googlesource.com/23970

**Comment by crhym3** [comment]
I have successfully ran a static file server using the CL 23970 referenced above. My program was:

```go
package main

import (
	"crypto/tls"
	"log"
	"net/http"

	"golang.org/x/crypto/acme/internal/manager"
)

func main() {
	dir := http.Dir(".")
	http.Handle("/", http.FileServer(dir))

	var man manager.Manager
	getcert := func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
		log.Printf("hello: %s", hello.ServerName)
		cert, err := man.GetCertificate(hello)
		if err != nil {
			log.Printf("mananger: %v", err)
		}
		return cert, err
	}

	s := &http.Server{
		Addr:      ":https",
		TLSConfig: &tls.Config{GetCertificate: getcert},
	}
	go func() {
		if err := s.ListenAndServeTLS("", ""); err != nil {
			log.Fatalf("serve TLS: %v", err)
		}
	}()

	if err := http.ListenAndServe(":http", nil); err != nil {
		log.Fatalf("serve http: %v", err)
	}
}
```

**Comment by crhym3** [comment]
@bradrydzewski this is now fixed! you can now use [golang.org/x/crypto/acme/autocert](https://golang.org/x/crypto/acme/autocert).
