### ISSUE TITLE
Pass urls map (Endpoint) to acme Client

### ISSUE THREAD

**Issue by mbwalas** [google/acme#16]
That way we could skip `url string` param in each call to the client. Maybe provide `Endpoint` as additional parameter to acme client, maybe additional wrapper.

**Comment by crhym3** [comment]
I see what you mean. Some of the `url` args of the client refer to an account URI, not Endpoint.
Do you think it would make sense to merge `Account` and `Client` at this point? Otherwise, it may feel inconsistent - some method will require url, others wont'

**Comment by crhym3** [comment]
For instance, [Register](https://github.com/google/goacme/blob/114453a7fd2e33f4f7887012456ea2eb326ccf84/acme.go#L173) indeed takes an `Endpoint` url, while [GetReg](https://github.com/google/goacme/blob/114453a7fd2e33f4f7887012456ea2eb326ccf84/acme.go#L179) requires `Account.URI`.

**Comment by crhym3** [comment]
Fixing this in https://go-review.googlesource.com/23972.

**Comment by crhym3** [comment]
Fixed by https://github.com/golang/crypto/commit/c2f4947f41766b144bb09066e919466da5eddeae.
(already synched this repo with that change)
