### ISSUE TITLE
Add support for wildcard certificates/ multiple CN names

### ISSUE THREAD

**Issue by chr4** [google/acme#31]
Requesting a wildcard certificate seems to not be possible at the moment:

```shell
$ acme cert *.example.com
*.example.com: 400 urn:acme:error:malformed: Error creating new authz :: Invalid character in DNS name
```

**Comment by chr4** [comment]
I just stumbled upon several people asking for support for wildcard certificates on letsencrypt, and I'm not sure whether it's actually possible with ACME at the moment.

Supporting multiple CN names should be possible, though.

**Comment by crhym3** [comment]
I'm afraid this won't work. Let's Encrypt doesn't allow wildcard certs: https://community.letsencrypt.org/t/frequently-asked-questions-faq/26

However, you can do SAN. For instance, this should work:

    acme cert one.example.com two.example.com
