### ISSUE TITLE
ECDSA keys

### ISSUE THREAD

**Issue by nhooyr** [google/acme#37]
Will there be support for ECDSA keys soon?

**Comment by nhooyr** [comment]
I'll try and cook up a PR tomorrow.

**Comment by crhym3** [comment]
@nhooyr sounds good.
You may also find https://github.com/google/acme/pull/34 very useful.

**Comment by nhooyr** [comment]
@crhym3 Before I submit a PR, I have a question about the API. In #34 you did not like how there was merely a comment above `Key crypto.Signer` that said `Key.Pub()` be an RSA key. How should I go about implementing this? Do you have any specific ideas in mind?

**Comment by crhym3** [comment]
Hey @nhooyr, sorry went off for a long weekend. When I commented on #34, he was just doing conversion without time checking, something like:

```go
var key crypto.Signer
key.(*rsa.PrivateKey)
```

which would obviously panic, not a good approach in this case. But the diff you show here is much better now: I can see the type checking and errors when an unsupported key is provided, which is what I was suggesting in #34.

**Comment by nhooyr** [comment]
Alright, I understand. I'll prepare a PR with something similar to the above diff.

**Comment by nhooyr** [comment]
@crhym3 `crypto/acme/internal/acme` and this repository seem to differ. I think `crypto/acme/internal/acme` is newer so I'm gonna create the PR there.

**Comment by crhym3** [comment]
yes, please, do it in crypto. I still need to sync this one with crypto/acme. will do it soon as I need to make sure cmd/acme works with the recent updates - that is the main reason I haven't done it yet.

**Comment by nhooyr** [comment]
Submitted. Once you sync this with `crypto/acme`, we should add ECDSA support into the acme command as well.

**Comment by crhym3** [comment]
Sounds good. For reference to others, the CL in question is here: https://go-review.googlesource.com/25462.

**Comment by nhooyr** [comment]
As a side note, is there anything I can do to help with developing the manager? https://go-review.googlesource.com/#/c/23970/

I need this sort of functionality in a program I am writing but I do not want to write everything myself and then switch to the standard library later.

**Comment by crhym3** [comment]
Sure. The plan for the manager is to support TLS-SNI challenges. It will do so using lower lever client API which is essentially done: https://go-review.googlesource.com/25450.

Once 25450 is submitted, we can go back to the manager, adjust its API and start implementing it. It shouldn't be too long once we figure out the best set of the manager API to expose.

**Comment by crhym3** [comment]
Fixed by https://github.com/golang/crypto/commit/e0d166c33c321d0ff863f459a5882096e334f508
